client:
  host: "localhost:3000"
  newRailsTutorial: "http://news.railstutorial.org/"
validate:
  maxName: 50
  maxEmail: 255
  minPass: 6
  validEmail: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
gravatar:
  size: 80
  host: "http://gravatar.com/emails"
  size2: 50
user_per_page: 20
