client:
  host: "localhost:3000"
  newRailsTutorial: "http://news.railstutorial.org/"
validate:
  maxName: 50
  maxEmail: 255
  minPass: 6
  validEmail: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
